import '../models/user_model.dart';
import '../models/ticket_model.dart';
import '../models/notification_model.dart';

class DummyData {
  static final List<UserModel> users = [
    UserModel(
      id: 'u001',
      name: 'Budi Santoso',
      email: 'budi@company.com',
      username: 'budi',
      password: '123456',
      role: 'user',
      department: 'Finance',
      avatar: 'BS',
      phone: '081234567890',
    ),
    UserModel(
      id: 'u002',
      name: 'Siti Rahayu',
      email: 'siti@company.com',
      username: 'siti',
      password: '123456',
      role: 'user',
      department: 'HR',
      avatar: 'SR',
      phone: '082345678901',
    ),
    UserModel(
      id: 'u003',
      name: 'Andi Wijaya',
      email: 'andi@company.com',
      username: 'andi',
      password: '123456',
      role: 'user',
      department: 'Marketing',
      avatar: 'AW',
      phone: '083456789012',
    ),
    UserModel(
      id: 'h001',
      name: 'Rizky Prasetyo',
      email: 'rizky@company.com',
      username: 'rizky',
      password: '123456',
      role: 'helpdesk',
      department: 'IT Support',
      avatar: 'RP',
      phone: '084567890123',
    ),
    UserModel(
      id: 'h002',
      name: 'Dewi Kusuma',
      email: 'dewi@company.com',
      username: 'dewi',
      password: '123456',
      role: 'helpdesk',
      department: 'IT Support',
      avatar: 'DK',
      phone: '085678901234',
    ),
    UserModel(
      id: 'a001',
      name: 'Admin Utama',
      email: 'admin@company.com',
      username: 'admin',
      password: 'admin123',
      role: 'admin',
      department: 'IT',
      avatar: 'AU',
      phone: '086789012345',
    ),
  ];

  static List<TicketModel> tickets = [
    TicketModel(
      id: 'TKT-001',
      title: 'Laptop tidak bisa menyala',
      description: 'Laptop saya tiba-tiba tidak mau menyala setelah update Windows kemarin. Sudah dicoba restart tapi tetap tidak bisa.',
      category: 'Hardware',
      priority: 'high',
      status: 'in progress',
      createdById: 'u001',
      createdByName: 'Budi Santoso',
      assignedToId: 'h001',
      assignedToName: 'Rizky Prasetyo',
      createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 3)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 5)),
      comments: [
        CommentModel(
          id: 'c001',
          ticketId: 'TKT-001',
          authorId: 'h001',
          authorName: 'Rizky Prasetyo',
          authorRole: 'helpdesk',
          content: 'Halo Pak Budi, saya sedang memeriksa masalah ini. Bisa tolong coba tekan tombol power selama 30 detik?',
          createdAt: DateTime.now().subtract(const Duration(hours: 10)),
        ),
        CommentModel(
          id: 'c002',
          ticketId: 'TKT-001',
          authorId: 'u001',
          authorName: 'Budi Santoso',
          authorRole: 'user',
          content: 'Sudah dicoba tapi masih tidak bisa menyala Pak.',
          createdAt: DateTime.now().subtract(const Duration(hours: 8)),
        ),
      ],
      history: [
        TicketHistoryModel(
          id: 'h001',
          ticketId: 'TKT-001',
          action: 'Tiket dibuat',
          performedBy: 'Budi Santoso',
          performedByRole: 'user',
          timestamp: DateTime.now().subtract(const Duration(days: 2, hours: 3)),
        ),
        TicketHistoryModel(
          id: 'h002',
          ticketId: 'TKT-001',
          action: 'Tiket di-assign ke Rizky Prasetyo',
          performedBy: 'Admin Utama',
          performedByRole: 'admin',
          timestamp: DateTime.now().subtract(const Duration(days: 2)),
        ),
        TicketHistoryModel(
          id: 'h003',
          ticketId: 'TKT-001',
          action: 'Status diubah menjadi In Progress',
          performedBy: 'Rizky Prasetyo',
          performedByRole: 'helpdesk',
          timestamp: DateTime.now().subtract(const Duration(hours: 10)),
        ),
      ],
    ),
    TicketModel(
      id: 'TKT-002',
      title: 'Email tidak bisa terkirim',
      description: 'Saat mencoba mengirim email ke klien, selalu muncul error "SMTP connection failed". Ini sudah berlangsung sejak 2 hari lalu.',
      category: 'Software',
      priority: 'medium',
      status: 'open',
      createdById: 'u002',
      createdByName: 'Siti Rahayu',
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      comments: [],
      history: [
        TicketHistoryModel(
          id: 'h004',
          ticketId: 'TKT-002',
          action: 'Tiket dibuat',
          performedBy: 'Siti Rahayu',
          performedByRole: 'user',
          timestamp: DateTime.now().subtract(const Duration(days: 1)),
        ),
      ],
    ),
    TicketModel(
      id: 'TKT-003',
      title: 'Printer offline di lantai 3',
      description: 'Printer Canon IP2770 di ruang Marketing lantai 3 menampilkan status offline dan tidak bisa digunakan.',
      category: 'Hardware',
      priority: 'low',
      status: 'resolved',
      createdById: 'u003',
      createdByName: 'Andi Wijaya',
      assignedToId: 'h002',
      assignedToName: 'Dewi Kusuma',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
      comments: [
        CommentModel(
          id: 'c003',
          ticketId: 'TKT-003',
          authorId: 'h002',
          authorName: 'Dewi Kusuma',
          authorRole: 'helpdesk',
          content: 'Printer sudah diperbaiki. Masalahnya adalah kabel USB yang longgar. Silakan coba lagi.',
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
        ),
      ],
      history: [
        TicketHistoryModel(
          id: 'h005',
          ticketId: 'TKT-003',
          action: 'Tiket dibuat',
          performedBy: 'Andi Wijaya',
          performedByRole: 'user',
          timestamp: DateTime.now().subtract(const Duration(days: 5)),
        ),
        TicketHistoryModel(
          id: 'h006',
          ticketId: 'TKT-003',
          action: 'Status diubah menjadi Resolved',
          performedBy: 'Dewi Kusuma',
          performedByRole: 'helpdesk',
          timestamp: DateTime.now().subtract(const Duration(days: 1)),
        ),
      ],
    ),
    TicketModel(
      id: 'TKT-004',
      title: 'Akses VPN gagal',
      description: 'Tidak bisa terhubung ke VPN perusahaan saat bekerja dari rumah. Error yang muncul: "Authentication failed".',
      category: 'Network',
      priority: 'high',
      status: 'pending',
      createdById: 'u001',
      createdByName: 'Budi Santoso',
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 6)),
      comments: [],
      history: [
        TicketHistoryModel(
          id: 'h007',
          ticketId: 'TKT-004',
          action: 'Tiket dibuat',
          performedBy: 'Budi Santoso',
          performedByRole: 'user',
          timestamp: DateTime.now().subtract(const Duration(hours: 6)),
        ),
      ],
    ),
    TicketModel(
      id: 'TKT-005',
      title: 'Software akuntansi crash',
      description: 'Aplikasi Accurate versi terbaru sering crash ketika membuka laporan bulanan. Sudah coba reinstall tapi masalah tetap ada.',
      category: 'Software',
      priority: 'high',
      status: 'closed',
      createdById: 'u002',
      createdByName: 'Siti Rahayu',
      assignedToId: 'h001',
      assignedToName: 'Rizky Prasetyo',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updatedAt: DateTime.now().subtract(const Duration(days: 7)),
      comments: [
        CommentModel(
          id: 'c004',
          ticketId: 'TKT-005',
          authorId: 'h001',
          authorName: 'Rizky Prasetyo',
          authorRole: 'helpdesk',
          content: 'Masalah sudah diselesaikan dengan update driver graphics card. Harap konfirmasi.',
          createdAt: DateTime.now().subtract(const Duration(days: 7, hours: 2)),
        ),
        CommentModel(
          id: 'c005',
          ticketId: 'TKT-005',
          authorId: 'u002',
          authorName: 'Siti Rahayu',
          authorRole: 'user',
          content: 'Sudah berjalan normal. Terima kasih!',
          createdAt: DateTime.now().subtract(const Duration(days: 7)),
        ),
      ],
      history: [
        TicketHistoryModel(
          id: 'h008',
          ticketId: 'TKT-005',
          action: 'Tiket dibuat',
          performedBy: 'Siti Rahayu',
          performedByRole: 'user',
          timestamp: DateTime.now().subtract(const Duration(days: 10)),
        ),
        TicketHistoryModel(
          id: 'h009',
          ticketId: 'TKT-005',
          action: 'Status diubah menjadi Closed',
          performedBy: 'Admin Utama',
          performedByRole: 'admin',
          timestamp: DateTime.now().subtract(const Duration(days: 7)),
        ),
      ],
    ),
    TicketModel(
      id: 'TKT-006',
      title: 'Monitor berkedip-kedip',
      description: 'Monitor di meja saya berkedip-kedip sejak kemarin. Sudah ganti kabel tapi masih sama.',
      category: 'Hardware',
      priority: 'medium',
      status: 'open',
      createdById: 'u003',
      createdByName: 'Andi Wijaya',
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
      updatedAt: DateTime.now().subtract(const Duration(hours: 12)),
      comments: [],
      history: [
        TicketHistoryModel(
          id: 'h010',
          ticketId: 'TKT-006',
          action: 'Tiket dibuat',
          performedBy: 'Andi Wijaya',
          performedByRole: 'user',
          timestamp: DateTime.now().subtract(const Duration(hours: 12)),
        ),
      ],
    ),
  ];

  static List<NotificationModel> notifications = [
    NotificationModel(
      id: 'n001',
      title: 'Tiket TKT-001 diperbarui',
      body: 'Status tiket "Laptop tidak bisa menyala" diubah menjadi In Progress',
      ticketId: 'TKT-001',
      type: 'status_update',
      isRead: false,
      createdAt: DateTime.now().subtract(const Duration(hours: 10)),
    ),
    NotificationModel(
      id: 'n002',
      title: 'Komentar baru di TKT-001',
      body: 'Rizky Prasetyo menambahkan komentar pada tiket Anda',
      ticketId: 'TKT-001',
      type: 'new_comment',
      isRead: false,
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
    ),
    NotificationModel(
      id: 'n003',
      title: 'Tiket TKT-003 diselesaikan',
      body: 'Tiket "Printer offline di lantai 3" telah diselesaikan',
      ticketId: 'TKT-003',
      type: 'resolved',
      isRead: true,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
  ];
}
